import { defineConfig, devices } from "@playwright/test";
import path from "path";

// Auth state files per role (generated by global-setup)
export const STORAGE_STATE_OWNER  = path.join(__dirname, "tests/.auth/owner.json");
export const STORAGE_STATE_ADMIN  = path.join(__dirname, "tests/.auth/admin.json");
export const STORAGE_STATE_COACH  = path.join(__dirname, "tests/.auth/coach.json");
export const STORAGE_STATE_MEMBER = path.join(__dirname, "tests/.auth/member.json");
export const STORAGE_STATE_SCHOOL = path.join(__dirname, "tests/.auth/school.json");

export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: 1,

  // Global setup — login setiap role dan simpan storageState
  globalSetup: "./tests/global-setup.ts",

  reporter: [
    ["html", { outputFolder: "playwright-report", open: "never" }],
    ["list"],
  ],

  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "on-first-retry",
    actionTimeout: 15_000,
    navigationTimeout: 30_000,
  },

  projects: [
    // ── Public tests — tidak butuh auth ───────────────────────────────────────
    {
      name: "public",
      testMatch: /\/(01-landing|02-login|03-register)\.spec\.ts/,
      use: { ...devices["Desktop Chrome"] },
    },

    // ── Public tests — mobile viewport ────────────────────────────────────────
    {
      name: "public-mobile",
      testMatch: /\/(01-landing|02-login|03-register)\.spec\.ts/,
      use: { ...devices["Pixel 7"] },
    },

    // ── Owner panel ───────────────────────────────────────────────────────────
    {
      name: "owner",
      testMatch: /04-owner-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_OWNER,
      },
    },

    // ── Admin panel ───────────────────────────────────────────────────────────
    {
      name: "admin",
      testMatch: /05-admin-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_ADMIN,
      },
    },

    // ── Coach panel ───────────────────────────────────────────────────────────
    {
      name: "coach",
      testMatch: /06-coach-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_COACH,
      },
    },

    // ── Member panel ──────────────────────────────────────────────────────────
    {
      name: "member",
      testMatch: /07-member-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_MEMBER,
      },
    },

    // ── School panel ──────────────────────────────────────────────────────────
    {
      name: "school",
      testMatch: /08-school-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_SCHOOL,
      },
    },

    // ── Flow tests — CRUD & integration (pakai storageState yang sama) ────────
    {
      name: "flow-owner",
      testMatch: /09-flow-owner-crud\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_OWNER,
      },
    },
    {
      name: "flow-admin",
      testMatch: /10-flow-admin-crud\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_ADMIN,
      },
    },
    {
      name: "flow-coach",
      testMatch: /11-flow-coach-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_COACH,
      },
    },
    {
      name: "flow-member",
      testMatch: /12-flow-member-panel\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: STORAGE_STATE_MEMBER,
      },
    },
  ],

  webServer: {
    command: "npm run dev",
    url: "http://localhost:3000",
    reuseExistingServer: true,
    timeout: 120_000,
    stdout: "ignore",
    stderr: "ignore",
  },
});
